notenSystem/noten/urls.py
from django.urls import path

from . import views

from django.conf.urls import url
from django.contrib import admin


app_name = 'noten'
urlpatterns = [
    path('', views.index, name='IndexView'),
    path('logout/', views.logout_view, name='logout_view'),
    path('startseite_lehrer/', views.startseite_lehrer, name='startseite_lehrer'),
    path('startseite_schueler/', views.startseite_schueler, name='startseite_schueler'),
    path('<int:klasse_id>/detailseite_lehrer/', views.detailseite_lehrer,name='detailseite_lehrer'),
    path('<int:klasse_noten_id>/detailseite__lehrer', views.detailseite_notenvergebung_lehrer, name='detailseite_notenvergebung_lehrer'),
    path('<int:subject_id>/detailseite_schueler/', views.detailseite_schueler, name='detailseite_schueler'),
    path('<int:klasse_noten_id>/noteneintragung_lehrer/<int:student_id>', views.noteneintragung_lehrer, name="noteneintragung_lehrer"),
    path('<int:subject_id>/noteneintragung_lehrer/<int:student_id>/eintragen', views.note_eintragen, name="noten_eintragen"),
    url(r'^admin/', admin.site.urls),
]

notenSystem/notenSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from noten import views

app_name = 'noten'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noten.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

notenSystem/noten/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Klasse(models.Model):
    class_name = models.CharField(default="", max_length=150)

    def __str__(self):
        return self.class_name

class Student(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    klasse = models.ForeignKey(Klasse, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = "Students"

class Subject(models.Model):
    subject_name = models.CharField(default="", max_length=150)

    def __str__(self):
        return self.subject_name

class Unterricht(models.Model):
    Subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    Teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    Klasse = models.ForeignKey(Klasse, on_delete=models.CASCADE)

    def __str__(self):
        return self.Subject.subject_name

    class Meta:
        verbose_name_plural = "Unterrichte"

class Note(models.Model):
    note = models.IntegerField(default=0)
    type = models.CharField(default="", max_length=150)
    comment = models.CharField(default="", max_length=150)
    Student = models.ForeignKey(Student, on_delete=models.CASCADE)
    Unterricht = models.ForeignKey(Unterricht, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.Student.user.username

    class Meta:
        verbose_name_plural = "Noten"

notenSystem/notenSystem/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Student(models.Model):
    username = models.CharField(default="", max_length=250)
    password = models.CharField(default="", max_length=50)
    email = models.CharField(default="", max_length=150)
    klasse = models.CharField(max_length=50, default="")

class Teacher(models.Model):
    username = models.CharField(default="", max_length=250)
    password = models.CharField(default="", max_length=50)
    email = models.CharField(default="", max_length=150)
    Klasse = models.ForeignKey(Klasse, on_delete=models.CASCADE)

class Klasse(models.Model):
    class_name = models.CharField(default="", max_length=150)
    subjects = models.CharField(default="", max_length=150)
    teacher = models.CharField(default="", max_length=150)


class Subject(models.Model):
    noten = models.IntegerField(default=0)
    Klasse = models.ForeignKey(Klasse, on_delete=models.CASCADE)
    Teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    Student = models.ForeignKey(Student, on_delete=models.CASCADE)


class Noten(models.Model):
    noten = models.IntegerField(default=0)
    Student = models.ForeignKey(Student, on_delete=models.CASCADE)
    Subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    Klasse = models.ForeignKey(Klasse, on_delete=models.CASCADE)

notenSystem/noten/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, reverse
from django.contrib.auth import logout

from .models import Klasse, Student, Subject, Note, Unterricht, User

@login_required
def logout_view(request):
    logout(request)

    return render(request, 'registration/logout1.html')

@login_required
def index(request):
    usergroups = request.user.groups.all()
    names = []
    for g in usergroups:
        names.append(g.name)
        if 'Teacher' in names:
            return HttpResponseRedirect('/startseite_lehrer')
        elif 'Student' in names:
            return HttpResponseRedirect('/startseite_schueler')

@login_required
def startseite_lehrer(request):
    klassen = Klasse.objects.filter(unterricht__Teacher=request.user).distinct()

    return render(request , 'noten/startseite_lehrer.html', {'latest_klasse_list' : klassen})

@login_required
def startseite_schueler(request):
    subjects = Unterricht.objects.filter(Klasse__student__user = request.user)

    return render(request, 'noten/startseite_schueler.html', {'latest_subject_list' : subjects})

@login_required
def detailseite_lehrer(request, klasse_id):
    unterricht = Unterricht.objects.filter(Teacher=request.user, Klasse__id = klasse_id)

    return render(request, 'noten/detailseite_lehrer.html', {'latest_unterricht_list' : unterricht})

@login_required
def detailseite_schueler(request, subject_id):
    noten = Note.objects.filter(Student__user = request.user, Unterricht__id=subject_id)

    return render(request, 'noten/detailseite_schueler.html', {'latest_noten_liste' : noten})

@login_required
def detailseite_notenvergebung_lehrer(request, klasse_noten_id):
    notenvergebung = Student.objects.filter(klasse__unterricht__id= klasse_noten_id)

    return render(request, 'noten/detailseite_notenvergebung_lehrer.html', {'latest_student_list' : notenvergebung, 'klasse_noten_id' : klasse_noten_id})

@login_required
def noteneintragung_lehrer(request, klasse_noten_id, student_id):
    noteneintragung = Student.objects.all()
    noten = Note.objects.filter(Student= Student.objects.get(pk=student_id))

    return render(request, 'noten/noteneintragung_lehrer.html', {'subject_id': klasse_noten_id, 'student_id': student_id, 'latest_noten_list' : noten})


@login_required
def note_eintragen(request, subject_id, student_id):
    if request.POST:
        name = request.POST['examname']
        note = request.POST['note']
        comment = request.POST['comment']
        student = Student.objects.get(pk=student_id)
        n = Note(Unterricht=Unterricht.objects.get(pk=subject_id), Student=student, note=note, type=name, comment=comment)
        n.save()

        return HttpResponseRedirect(reverse('noten:noteneintragung_lehrer', args=(subject_id, student_id)))

notenSystem/noten/templates/noten/detailseite_lehrer.html
<!DOCTYPE html>
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" rel="stylesheet">

    <title>Marksystem</title>

    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="">Navbar</a>
    <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbarNav" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'noten:startseite_lehrer' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>

<div class="jumbotron text-center">
    <h1>Marksystem</h1>
    <script type='text/javascript'
                        src='https://darksky.net/widget/default-small/47.2654,11.3928/ca12/en.js?width=100%&height=70&title=Full Forecast&textColor=333333&bgColor=transparent&transparency=true&skyColor=undefined&fontFamily=Default&customFont=&units=ca'></script>
    <footer class="blockquote-footer">Here you can see your subjects.</footer>
</div>

{% if latest_unterricht_list %}
<div class="row ml-3">
    {% for unterricht in latest_unterricht_list %}
    <div class="card mr-3 mb-3" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ unterricht.Subject.subject_name }}</h5>
            <a class="btn btn-primary" href="{% url 'noten:detailseite_notenvergebung_lehrer' unterricht.id %}">Open</a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No subjects are available.</p>
{% endif %}

<style>
    html, body {
        overflow-x: hidden;
        height: 100%;
    }
</style>
</body>
</html>

notenSystem/noten/templates/noten/detailseite_notenvergebung_lehrer.html
<!DOCTYPE html>
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" rel="stylesheet">

    <title>Marksystem</title>

    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="">Navbar</a>
    <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbarNav" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'noten:startseite_lehrer' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>


<div class="jumbotron text-center">
    <h1>Marksystem</h1>
    <script type='text/javascript'
                        src='https://darksky.net/widget/default-small/47.2654,11.3928/ca12/en.js?width=100%&height=70&title=Full Forecast&textColor=333333&bgColor=transparent&transparency=true&skyColor=undefined&fontFamily=Default&customFont=&units=ca'></script>
    <footer class="blockquote-footer">Here you can see all students participating in your subject.</footer>
</div>

{% if latest_student_list %}
<div class="row ml-3">
    {% for student in latest_student_list %}
    <div class="card mb-3 mr-3" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ student.user.first_name }} {{ student.user.last_name}}</h5>
            <a class="btn btn-primary" href="{% url 'noten:noteneintragung_lehrer' klasse_noten_id student.id%}">Open</a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No Students are available.</p>
{% endif %}

<style>
    html, body {
        overflow-x: hidden;
        height: 100%;
    }
</style>
</body>
</html>

notenSystem/noten/templates/noten/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

notenSystem/noten/templates/noten/noteneintragung_lehrer.html
<!DOCTYPE html>
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" rel="stylesheet">

    <title>Marksystem</title>

    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="">Navbar</a>
    <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbarNav" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'noten:startseite_lehrer' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>

<div class="jumbotron text-center">
    <h1>Marksystem</h1>
    <script type='text/javascript'
            src='https://darksky.net/widget/default-small/47.2654,11.3928/ca12/en.js?width=100%&height=70&title=Full Forecast&textColor=333333&bgColor=transparent&transparency=true&skyColor=undefined&fontFamily=Default&customFont=&units=ca'></script>
    <footer class="blockquote-footer">Here you can give grades to the respective students.</footer>
</div>

<form action="{% url 'noten:noten_eintragen' subject_id student_id %}" method="POST">
    {% csrf_token %}
    <div class="form-group row ml-3">
        <label for="exam" class="col-sm-2 col-form-label">Exam</label>
        <div class="col-sm-20">
            <input type="text" class="form-control" id="exam" placeholder="Exam" name="examname">
        </div>
    </div>

    <div class="form-group row ml-3">
        <label for="comment" class="col-sm-2 col-form-label"> Comment </label>
        <div class="col-sm-20">
            <input type="text" class="form-control" id="comment" placeholder="Comment" name="comment">
        </div>
    </div>

    <fieldset class="form-group">
        <div class="row ml-3">
            <legend class="col-form-label col-sm-2 pt-0">Mark</legend>
            <div class="col-sm-10">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="note" id="gridRadios1" value="1">
                    <label class="form-check-label" for="gridRadios1">
                        1
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="note" id="gridRadios2" value="2">
                    <label class="form-check-label" for="gridRadios2">
                        2
                    </label>
                </div>
                <div class="form-check disabled">
                    <input class="form-check-input" type="radio" name="note" id="gridRadios3" value="3">
                    <label class="form-check-label" for="gridRadios3">
                        3
                    </label>
                </div>
                <div class="form-check disabled">
                    <input class="form-check-input" type="radio" name="note" id="gridRadios4" value="4">
                    <label class="form-check-label" for="gridRadios3">
                        4
                    </label>
                </div>
                <div class="form-check disabled">
                    <input class="form-check-input" type="radio" name="note" id="gridRadios5" value="5">
                    <label class="form-check-label" for="gridRadios3">
                        5
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary row ml-4">Send Mark!</button>
            </div>
        </div>
</form>

<table class="table table-striped" id="table">
    <thead>
    <tr>
        <th scope="col">Number</th>
        <th scope="col">Mark</th>
        <th scope="col">Description</th>
        <th scope="col">Comment</th>
    </tr>
    </thead>
    <tbody>
    {% for noten in latest_noten_list %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ noten.note }}</td>
            <td> {{ noten.type }}</td>
            <td> {{ noten.comment }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<style>
    html, body {
        overflow-x: hidden;
        height: 100%;
    }

    #table {
        overflow-x: fragments;
    }
</style>

</body>
</html>

notenSystem/noten/templates/noten/startseite_lehrer.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" rel="stylesheet">

    <title>Marksystem</title>
    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="">Navbar</a>
    <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbarNav" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'noten:startseite_lehrer' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>

<div class="jumbotron text-center">
    <h1>Marksystem</h1>
    <script type='text/javascript'
            src='https://darksky.net/widget/default-small/47.2654,11.3928/ca12/en.js?width=100%&height=70&title=Full Forecast&textColor=333333&bgColor=transparent&transparency=true&skyColor=undefined&fontFamily=Default&customFont=&units=ca'></script>
    <footer class="blockquote-footer">Here you can see your classes in which you teach.</footer>
</div>

{% if latest_klasse_list %}
<div class="row ml-3">
    {% for klasse in latest_klasse_list %}
    <div class="card mr-3 mb-3" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ klasse.class_name }}</h5>
            <a class="btn btn-primary" href="{% url 'noten:detailseite_lehrer' klasse.id %}">Open</a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No classes are available.</p>
{% endif %}

<style>
    html, body {
        overflow-x: hidden;
        height: 100%;
    }
</style>
</body>
</html>

notenSystem/noten/templates/noten/startseite_schueler.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" rel="stylesheet">

    <title>Marksystem</title>
    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="">Navbar</a>
    <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbarNav" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'noten:startseite_schueler' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>

<div class="jumbotron text-center">
    <h1>Marksystem</h1>
    <script type='text/javascript'
            src='https://darksky.net/widget/default-small/47.2654,11.3928/ca12/en.js?width=100%&height=70&title=Full Forecast&textColor=333333&bgColor=transparent&transparency=true&skyColor=undefined&fontFamily=Default&customFont=&units=ca'></script>
    <footer class="blockquote-footer">Here you can see your subjects.</footer>
</div>

{% if latest_subject_list %}
    <div class="row ml-3">
        {% for subject in latest_subject_list %}
            <div class="card mr-3 mb-3" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ subject.Subject.subject_name }}</h5>
                    <a class="btn btn-primary" href="{% url 'noten:detailseite_schueler' subject.id %}">Open</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p>No subjects are available.</p>
{% endif %}

<style>
    html, body {
        overflow-x: hidden;
        height: 100%;
    }
</style>
</body>
</html>